import type { Metadata } from "next";
import "./globals.css";
import { kastelov, verdana } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${verdana.variable} ${kastelov.variable}`}>
        {children}
      </body>
    </html>
  );
}
